#!/bin/bash -i

#TODO pass argument into file

# if first passed argument is empty, then
if [ -z $1 ]; then
echo "what repo???"
read repo
else
repo=$1
fi

# if the repo has already been downloaded...
if [ -f ./$repo/ ]; then
echo "this repo already exists..."
echo "remove with:"
echo "rm -rf $repo"
echo
exit
fi

url="https://github.com/suchdatums/$repo"
git clone --recurse-submodules $url
rm -rf ./$repo/.git
rm ./$repo/.gitignore

echo ">>> DO YOU WANT TO INSTALL IN THE HOME FOLDER?"
echo "type: yes"
read inp
if [ $inp != "yes" ]; then
exit
fi
cp -rf ./$repo/* .
rm -r ./$repo/
