#!/bin/bash -i

repo="dotfile"
url="https://github.com/suchdatums/$repo"
git clone --depth=1 $url
rm -rf ./$repo/.git
mv -f ./$repo/* .
rm -r ./$repo/
mv -f bash_aliases .bash_aliases
chmod +x getdot getrepo

# VERSION
ver=9003
clear
echo
echo "VERSION: <<< $ver >>>"
echo
ls -gop --human-readable --sort=extension --group-directories-first --color=auto
echo -e "\n\nhey... run this command to finish up\n\nsource .bashrc"

# BUG
# if this file is executable, then use '.' instead of 'source'
# but it's not working...
#. .bashrc
