#!/bin/bash -i

# this file will update itself when ran

repo="dotfile"
url="https://github.com/suchdatums/$repo"
git clone --depth=1 $url
rm -rf ./$repo/.git
mv -f ./$repo/* .
rm -r ./$repo/
mv -f bash_aliases .bash_aliases
chmod +x getdot get_repo
clear
ls -gop --human-readable

echo
echo "VERSION 1.8"
echo
echo "to update again, just type: dot"

source .bashrc
