#!/bin/bash -i

#cd ~

# make deletable (mutible), if exists
if [ -f ./getrepo ]; then
    sudo chattr -i getrepo
fi

repo="dotfile"
url="https://github.com/suchdatums/$repo"
git clone --depth=1 $url
rm -rf ./$repo/.git
# move file out of repo folder to <here>
mv -f ./$repo/* .

# move dot files out of repo folder to <here>
#mv -f ./$repo/.* 

# delete repo folder
rm -r ./$repo/

# make them dot files
mv -f bash_aliases .bash_aliases
mf -f installdot .installdot
mv -f getdot .getdot
mv -f helpdot .helpdot
mv -f tmux.conf .tmux.conf

# make these executable
chmod +x .getdot getrepo

# make safe from deletion
sudo chattr +i getrepo

# to have version number show up
. ./.bash_aliases

touch .dot$DOT_VERSION

########
#clear
ls -gop --human-readable --sort=extension --group-directories-first --color=auto
echo ">> VERSION: $DOT_VERSION"
echo ">> 'helpdot' for help"
echo
echo 
echo "RUN THIS: source .bash_aliases"
