#!/bin/bash -i

# if first passed argument is empty, then
if [ -z $1 ]; then
        echo "what repo???"
        read repo
    else
        repo=$1
fi

# if the repo has already been downloaded...
if [ -d ./$repo/ ]; then
    echo "this repo already exists..."
    echo "remove with:  'rm -rf $repo'  (?)  type yes if yes"
    read inp
    if [ -eq $inp "yes" ]; then
        rm -rf ./$repo
    else
        echo "exiting..."
        exit
fi

# get repo and tidy up
url="https://github.com/suchdatums/$repo"
    git clone --recurse-submodules --remote-submodules $url
    # TODO 
    # how can I recurse into every subdir and delete the .git file?
    # can can I do this safely without destorying any project I may be working on?
    # I only want to go into the DOWNLOADED submodules and delete the .git folder... hmmm.
    rm -rf ./$repo/.git
    rm ./$repo/.gitignore

# make scripts executable
cd $repo
    # loop through every non-hidden file in directory
    for FILE in $(files); do
        # if she bang
        if [ "`head -c 2 $FILE`" = "#!" ]; then
            # made executable
            chmod +x $FILE
        fi
    done
back


show $repo
echo
echo
echo "RUN THIS TO INSTALL INTO HOME FOLDER:"
echo "cp -rf ./$repo/* . && rm -r ./$repo/"
