#!/bin/bash -i

# if first passed argument is empty, then
if [ -z $1 ]; then
echo "what repo???"
read repo
else
repo=$1
fi

echo getting $repo

# if the repo has already been downloaded...
if [ -d ./$repo/ ]; then
echo "this repo already exists..."
echo "remove with:"
echo "rm -rf $repo"
echo
exit
fi

url="https://github.com/suchdatums/$repo"
git clone --recurse-submodules --remote-submodules $url

# TODO 
# how can I recurse into every subdir and delete the .git file?
# can can I do this safely without destorying any project I may be working on?
# I only want to go into the DOWNLOADED submodules and delete the .git folder... hmmm.
rm -rf ./$repo/.git
rm ./$repo/.gitignore

echo
echo ">>> DO YOU WANT TO INSTALL IN THE HOME FOLDER?"
echo "type: yes"
read inp
if [ $inp != "yes" ]; then
exit
fi
cp -rf ./$repo/* .
rm -r ./$repo/

echo
echo ">>> CHANGE PERMISSIONS TO SETUP_$repo?"
echo "type: yes"
read inp
if [ $inp != "yes" ]; then
exit
fi
chmod +x SETUP_$repo
