#!/bin/bash -i

cd ~
clear
echo "======================"
echo "INSTALL SCRIPT RUNNING"



# always remember to...
###################
cmds="
sudo raspi-config

sudo apt update -y
sudo apt upgrade -y
"
asktoinstall "$cmds"



# tidy up
###################
cmds="
rm -rf Bookshelf/ Documents/ Downloads/ Music/ Pictures/ Public/ Templates/ Videos/
"
asktoinstall "$cmds"




echo "done"
exit

# TEMPLATE
echo
echo "explain to the user right here"
###################
cmds="
echo 'put commands here'
echo 'careful with your quotes'
"
asktoinstall "$cmds"
